### ISSUE TITLE
Simplified Instructions

### ISSUE THREAD

**Issue by nelsonic** [dwyl/atm#2]
http://aslakhellesoy.com/post/11055981222/the-training-wheels-came-off

``` sh
Scenario: Successful login
  Given a user "Aslak" with password "xyz"
  And I am on the login page
  And I fill in "User name" with "Aslak"
  And I fill in "Password" with "xyz"
  When I press "Log in"
  Then I should see "Welcome, Aslak"
```

I would write this as:

``` sh
task "Login"
visit /login
input #username "Aslak"
input #password "xyz"
click #login
expect #welcomemessage "Welcome, Aslak"
```

@iteles Which reads better?

**Comment by iteles** [comment]
The second one reads much better. 
**Complete beginners** can be taught how to use that syntax a quick 'getting started' readme and it's **much easier** to read through when looking up tests.

**Comment by nelsonic** [comment]
see: https://github.com/dwyl/learn-nightmare-and-daydream 😉
