### ISSUE TITLE
Words   [ dictionary/glossary/wiki ]

### ISSUE THREAD

**Issue by nelsonic** [dwyl/atm#3]
> **_this comment can be edited by contributors**_. 

This is an alphabetical list of the words we have defined in the **_alvo**_ **vocabulary** with an explanation of what the word means (to us), the associated action it accomplishes and an example of its usage.
## expect

**expect** lets us _check_ something on the page.
## visit

**visit** is the simplest word we could think of for instructing a person to visit a particular url.  
example:  

```
visit google.com
expect pagehastext "I'm Feeling Lucky"
```

**Comment by nelsonic** [comment]
@iteles we are essentially developing our own http://en.wikipedia.org/wiki/Domain-specific_language for this project. we need a *fantastic* name for the ***new language*** for the web! :wink:

**Comment by iteles** [comment]
This. Is. So. Fun! :tada: :balloon:

**Comment by nelsonic** [comment]
What do you think about using the word ***first*** to indicate an task that you "*include*".
e.g:
```sh
first "login"
visit /new
input #tweet "inventing new dsl for the web!"
click #submit
expect .tweets contains "inventing new dsl"
```

**Comment by iteles** [comment]
@nelsonic I'm not sure what you mean by _"include"_. Please clarify? :blush:

**Comment by iteles** [comment]
Right. "include" and "import" aren't _**natural**_ for non-programmers.

**Comment by nelsonic** [comment]
as in **include** in C: https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html
*or* **include** in PHP: http://php.net/manual/en/function.include.php
*or* **import** in python: http://stackoverflow.com/questions/714881/how-to-include-external-python-code-to-use-in-other-files
*or* **include** in Ruby: http://stackoverflow.com/questions/318144/what-is-the-difference-between-include-and-require-in-ruby
*or* **require** in node.js ... https://docs.nodejitsu.com/articles/getting-started/what-is-require

Its another piece of code you want to include before running your statement.

**Comment by nelsonic** [comment]
we could use **require** instead of ***first***

**Comment by nelsonic** [comment]
I *really* want to keep the vocabulary as simple as possible. 
But... in fairness. ***require*** might be *clearer* because it could also do something *interesting*...
like if there is no ***task*** called "login" it could try and find one...

**Comment by iteles** [comment]
And `run` might be too intimidating for some people...

Yes. `require` sounds good! We can always change it if we have a flash of inspiration :zap:

**Comment by nelsonic** [comment]
No... that's the point of a DSL. we are carving the language into ***Stone***.
http://news.bbc.co.uk/1/hi/technology/8306631.stm

**Comment by iteles** [comment]
:laughing: No, I meant in the next few days!!
Might actually be interesting to talk to the _relatively inexperienced_ students coming in on Monday for the next cohort...

**Comment by nelsonic** [comment]
see: https://github.com/dwyl/learn-nightmare-and-daydream 👍
