### ISSUE TITLE
A Synchronous Task Runner ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/atm#5]
One of the difficult/interesting/fun parts of this quest is how to run a series of tasks across "pages".

The _easiest_ way is to have a boot script that reads the list of steps (e.g: from LocalStorage) and figures out which step still needs to be done. We then load the outstanding steps into a task runner.
## Why does the task runner need to be _Sync_hronous?

We need the tasks to be performed in a specific **_sequential**_ order the way a _person_ would interact with an application.

This is one of the few cases where using an [**async**](https://github.com/caolan/async) library is justifiable. We would use [**async.waterfall**](https://github.com/caolan/async#waterfall) because an error in any step terminates execution (no point going any further) whereas **async.series** would attempt to keep going...

[@Elan](https://github.com/es128) has kindly split out async.waterfall into a single file: https://github.com/es128/async-waterfall _sadly_, he _forgot_ to write tests... so... we can either write our own (can we simplify it?) _with_ **_tests**_ (quicker!) or Fork & PR (less fragmentation in the ecosystem).

![waterfall](http://i.imgur.com/IBK6L1W.jpg)

**Comment by nelsonic** [comment]
Going to make time to write some *retrospective* tests for this: https://github.com/es128/async-waterfall/issues/6

**Comment by iteles** [comment]
@nelsonic Looks to me like just a different way with handling issues - he just prefers to not have a question open if he's already answered it pending a PR

**Comment by nelsonic** [comment]
closing. no longer relevant. ✅
