### ISSUE TITLE
Proposed name for our ("new") Language?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/atm#7]
I've been racking my brains trying to come up with a good (_pref_ **_great**_!) name for the _language_ people will write their tests in...

So far, the "best" I've come up with is **_TEAL**_.
Which stands for **T**est**E**xecution**A**utomation**L**anguage
(also I quite like the color... https://www.google.co.uk/search?q=teal&es_sm=119&tbm=isch :wink: )

I'm _sure_ someone else will come up with a **_way better**_ name so I want to open up the discussion!

**Comment by iteles** [comment]
I quite like this name! ([and the colour](https://github.com/ideaq/time/issues/139)) but will put some thought into it

**Comment by nelsonic** [comment]
Sadly, teal and teal-lang are taken: https://github.com/teal-lang/teal :disappointed:

**Comment by nelsonic** [comment]
**B**rowser **A**utomation **T**est **E**xecution **L**anguage ...?

**Comment by nelsonic** [comment]
How about WAL **W**eb **A**utomation **L**anguage 
![npm-wal-available](https://cloud.githubusercontent.com/assets/194400/7671211/3d0b9f50-fcbc-11e4-86dc-06174be72bd4.png)
inspired by (but in no way copy-right or trademark infringing) http://en.wikipedia.org/wiki/WALL-E

**Comment by iteles** [comment]
:laughing: The Wall-E inspiration was the first thing I thought of too. But I like it. 

I thought of _**T**esting **i**n **E**nglish_ but that's already taken by [many many things](https://www.npmjs.com/search?q=tie)

**Comment by nelsonic** [comment]
Ok. I think I'm just going to use **WAL** to get this started. we can always change it laters. :+1:

**Comment by nelsonic** [comment]
@iteles how would you pronounce: "ial"

**Comment by iteles** [comment]
"ial" I'd probably pronounce as 'aisle' (the Portuguese side of my brain would hit the 'i' and pronounce it similar to 'yell'). But "ieal" would just look confusing and I every time I mentioned it I'd probably offer two pronunciations and end the sentence with "... or however you pronounce that".

Neither of them are names one would feel confident launching into in intelligent company though... The first far more so than the second.

**Comment by nelsonic** [comment]
This is *hard*!! what are your ideas...?

**Comment by iteles** [comment]
On ice for now?

**Comment by nelsonic** [comment]
Maybe not... :wink:

**Comment by nelsonic** [comment]
see: https://github.com/dwyl/learn-nightmare-and-daydream. 
closing. 👍
